platform :ios, "11.0"
use_frameworks! :linkage => :static

source "https://github.com/CocoaPods/Specs.git"

def pod_YPCoreKit
  pod "YPCoreKit", :path => ".."
end

def pod_ThirdFrameworks
  pod 'Kingfisher'
end

target 'YPCoreKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YPCoreKit

  pod_YPCoreKit
  pod_ThirdFrameworks

end
